<?php

namespace Proxies\__CG__\AppBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Settings extends \AppBundle\Entity\Settings implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', '' . "\0" . 'AppBundle\\Entity\\Settings' . "\0" . 'id', '' . "\0" . 'AppBundle\\Entity\\Settings' . "\0" . 'reportEmail', '' . "\0" . 'AppBundle\\Entity\\Settings' . "\0" . 'contactEmail', '' . "\0" . 'AppBundle\\Entity\\Settings' . "\0" . 'sendMessageUsersNumber', '' . "\0" . 'AppBundle\\Entity\\Settings' . "\0" . 'usersPerPage', '' . "\0" . 'AppBundle\\Entity\\Settings' . "\0" . 'isCharge', '' . "\0" . 'AppBundle\\Entity\\Settings' . "\0" . 'messagePopularityDaysNumber', '' . "\0" . 'AppBundle\\Entity\\Settings' . "\0" . 'userConsideredAsOnlineAfterLastActivityMinutesNumber', '' . "\0" . 'AppBundle\\Entity\\Settings' . "\0" . 'deleteMessagesAfterDaysNumber', '' . "\0" . 'AppBundle\\Entity\\Settings' . "\0" . 'userConsideredAsNewAfterDaysNumber');
        }

        return array('__isInitialized__', '' . "\0" . 'AppBundle\\Entity\\Settings' . "\0" . 'id', '' . "\0" . 'AppBundle\\Entity\\Settings' . "\0" . 'reportEmail', '' . "\0" . 'AppBundle\\Entity\\Settings' . "\0" . 'contactEmail', '' . "\0" . 'AppBundle\\Entity\\Settings' . "\0" . 'sendMessageUsersNumber', '' . "\0" . 'AppBundle\\Entity\\Settings' . "\0" . 'usersPerPage', '' . "\0" . 'AppBundle\\Entity\\Settings' . "\0" . 'isCharge', '' . "\0" . 'AppBundle\\Entity\\Settings' . "\0" . 'messagePopularityDaysNumber', '' . "\0" . 'AppBundle\\Entity\\Settings' . "\0" . 'userConsideredAsOnlineAfterLastActivityMinutesNumber', '' . "\0" . 'AppBundle\\Entity\\Settings' . "\0" . 'deleteMessagesAfterDaysNumber', '' . "\0" . 'AppBundle\\Entity\\Settings' . "\0" . 'userConsideredAsNewAfterDaysNumber');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Settings $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', array());

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setReportEmail($reportEmail)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setReportEmail', array($reportEmail));

        return parent::setReportEmail($reportEmail);
    }

    /**
     * {@inheritDoc}
     */
    public function getReportEmail()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getReportEmail', array());

        return parent::getReportEmail();
    }

    /**
     * {@inheritDoc}
     */
    public function setContactEmail($contactEmail)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setContactEmail', array($contactEmail));

        return parent::setContactEmail($contactEmail);
    }

    /**
     * {@inheritDoc}
     */
    public function getContactEmail()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getContactEmail', array());

        return parent::getContactEmail();
    }

    /**
     * {@inheritDoc}
     */
    public function setSendMessageUsersNumber($sendMessageUsersNumber)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSendMessageUsersNumber', array($sendMessageUsersNumber));

        return parent::setSendMessageUsersNumber($sendMessageUsersNumber);
    }

    /**
     * {@inheritDoc}
     */
    public function getSendMessageUsersNumber()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSendMessageUsersNumber', array());

        return parent::getSendMessageUsersNumber();
    }

    /**
     * {@inheritDoc}
     */
    public function setUsersPerPage($usersPerPage)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUsersPerPage', array($usersPerPage));

        return parent::setUsersPerPage($usersPerPage);
    }

    /**
     * {@inheritDoc}
     */
    public function getUsersPerPage()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUsersPerPage', array());

        return parent::getUsersPerPage();
    }

    /**
     * {@inheritDoc}
     */
    public function setIsCharge($isCharge)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIsCharge', array($isCharge));

        return parent::setIsCharge($isCharge);
    }

    /**
     * {@inheritDoc}
     */
    public function getIsCharge()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIsCharge', array());

        return parent::getIsCharge();
    }

    /**
     * {@inheritDoc}
     */
    public function setMessagePopularityDaysNumber($messagePopularityDaysNumber)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setMessagePopularityDaysNumber', array($messagePopularityDaysNumber));

        return parent::setMessagePopularityDaysNumber($messagePopularityDaysNumber);
    }

    /**
     * {@inheritDoc}
     */
    public function getMessagePopularityDaysNumber()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMessagePopularityDaysNumber', array());

        return parent::getMessagePopularityDaysNumber();
    }

    /**
     * {@inheritDoc}
     */
    public function setUserConsideredAsOnlineAfterLastActivityMinutesNumber($userConsideredAsOnlineAfterLastActivityMinutesNumber)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUserConsideredAsOnlineAfterLastActivityMinutesNumber', array($userConsideredAsOnlineAfterLastActivityMinutesNumber));

        return parent::setUserConsideredAsOnlineAfterLastActivityMinutesNumber($userConsideredAsOnlineAfterLastActivityMinutesNumber);
    }

    /**
     * {@inheritDoc}
     */
    public function getUserConsideredAsOnlineAfterLastActivityMinutesNumber()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUserConsideredAsOnlineAfterLastActivityMinutesNumber', array());

        return parent::getUserConsideredAsOnlineAfterLastActivityMinutesNumber();
    }

    /**
     * {@inheritDoc}
     */
    public function setDeleteMessagesAfterDaysNumber($deleteMessagesAfterDaysNumber)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDeleteMessagesAfterDaysNumber', array($deleteMessagesAfterDaysNumber));

        return parent::setDeleteMessagesAfterDaysNumber($deleteMessagesAfterDaysNumber);
    }

    /**
     * {@inheritDoc}
     */
    public function getDeleteMessagesAfterDaysNumber()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDeleteMessagesAfterDaysNumber', array());

        return parent::getDeleteMessagesAfterDaysNumber();
    }

    /**
     * {@inheritDoc}
     */
    public function setUserConsideredAsNewAfterDaysNumber($userConsideredAsNewAfterDaysNumber)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUserConsideredAsNewAfterDaysNumber', array($userConsideredAsNewAfterDaysNumber));

        return parent::setUserConsideredAsNewAfterDaysNumber($userConsideredAsNewAfterDaysNumber);
    }

    /**
     * {@inheritDoc}
     */
    public function getUserConsideredAsNewAfterDaysNumber()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUserConsideredAsNewAfterDaysNumber', array());

        return parent::getUserConsideredAsNewAfterDaysNumber();
    }

}
