imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: services.yml }

# Put parameters here that don't need to change on each machine where the app is deployed
# http://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    locale: en

framework:
    #esi:             ~
    #translator:      { fallbacks: ["%locale%"] }
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    #serializer:      { enable_annotations: true }
    templating:
        engines: ['twig']
        #assets_version: SomeVersionScheme
    default_locale:  "%locale%"
    trusted_hosts:   ~
    trusted_proxies: ~
    session:
        # handler_id set to null will use default session handler from php.ini
        handler_id:  ~
    fragments:       ~
    http_method_override: true

# Twig Configuration
twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"
    globals:
        messenger: "@messenger"

# Assetic Configuration
assetic:
    debug:          "%kernel.debug%"
    use_controller: false
    bundles:        [ ]
    #java: /usr/bin/java
    filters:
        cssrewrite: ~
        #closure:
        #    jar: "%kernel.root_dir%/Resources/java/compiler.jar"
        #yui_css:
        #    jar: "%kernel.root_dir%/Resources/java/yuicompressor-2.4.7.jar"

# DQL Configuration
doctrine:
    dbal:
        driver:   pdo_mysql
        host:     "%database_host%"
        port:     "%database_port%"
        dbname:   "%database_name%"
        user:     "%database_user%"
        password: "%database_password%"
        charset:  UTF8
        # if using pdo_sqlite as your database driver:
        #   1. add the path in parameters.yml
        #     e.g. database_path: "%kernel.root_dir%/data/data.db3"
        #   2. Uncomment database_path in parameters.yml.dist
        #   3. Uncomment next line:
        #     path:     "%database_path%"

    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true
        dql:
            numeric_functions:
                get_distance: AppBundle\DQL\GetDistanceFunction



# Swiftmailer Configuration
swiftmailer:
    transport: "%mailer_transport%"
    host:      "%mailer_host%"
    username:  "%mailer_user%"
    password:  "%mailer_password%"
    spool:     { type: memory }


services:
    SignUpFlow:
        class: AppBundle\Form\Type\SignUpFlow
        parent: craue.form.flow
        scope: request

    SignUpApiFlow:
        class: AppBundle\Form\Type\SignUpApiFlow
        #autoconfigure: true
        parent: craue.form.flow
        #scope: request

    activity_listener:
        class: AppBundle\EventListener\ActivityListener
        arguments: ['@security.token_storage', '@doctrine.orm.entity_manager']
        tags:
            - { name: kernel.event_listener, event: kernel.controller, method: onCoreController }

    login_listener:
        class: AppBundle\EventListener\LoginListener
        arguments: ['@security.token_storage', '@doctrine.orm.entity_manager']
        tags:
            - { name: kernel.event_listener, event: security.interactive_login}

#    ajax_listener:
#        class: AppBundle\EventListener\ApiAuthenticationListener
#        tags:
#            - { name: kernel.event_listener, event: kernel.exception, method: onCoreException, priority: 1000 }

    app.twig_extension:
        class: AppBundle\Twig\AppExtension
        arguments: ["@request_stack","@doctrine","@service_container","@messenger"]
        public: false
        tags:
            - { name: twig.extension }

    messenger:
        class:        AppBundle\Services\Messenger\Messenger
        arguments: ['@doctrine.orm.entity_manager']

    api_key_user_provider:
        class: AppBundle\Security\ApiKeyUserProvider
        arguments: ['@doctrine']

    apikey_authenticator:
        class: AppBundle\Security\ApiKeyAuthenticator
        arguments: ['@api_key_user_provider']

    api_user_provider:
        class: AppBundle\Security\ApiUserProvider
        arguments: ['@doctrine']

    api_authenticator:
        class: AppBundle\Security\ApiAuthenticator
        arguments: ['@api_user_provider', '@security.password_encoder']




assetic:
    debug:          "%kernel.debug%"
    use_controller: false
    bundles:        [ ]
    filters:
        cssrewrite: ~

# Nelmio CORS Configuration
nelmio_cors:
    defaults:
        allow_credentials: false
        allow_origin: ['*']
        allow_headers: ['*']
        allow_methods: ['GET', 'POST', 'PUT', 'DELETE', 'OPTIONS']
        max_age: 3600
        hosts: []
        origin_regex: false

# FOSRest Configuration
fos_rest:
    param_fetcher_listener: true
    body_listener:
        decoders:
            json: fos_rest.decoder.json
    format_listener: true

        #enabled: true
        #rules:
        #    - { path: '^/open_api', priorities: ['json'], fallback_format: json, prefer_extension: false }

        #    - { path: '^/api/doc', priorities: ['text/html', '*/*'], fallback_format: html, prefer_extension: true }
        #    - { path: '^/', priorities: ['text/html', '*/*'], fallback_format: html, prefer_extension: true }
        #    - { path: '^/api', priorities: ['json'], fallback_format: json, prefer_extension: false }
    view:
        view_response_listener: 'force'
    #body_listener: true
    #format_listener:
    #    rules:
    #        - { path: '^/', priorities: ['json'], fallback_format: json, prefer_extension: false }
   # param_fetcher_listener: true
    #view:
    #    view_response_listener: 'force'
    #    formats:
           # json: true
    routing_loader:
            default_format: json

nelmio_api_doc: ~

mobile_detect:
    redirect:
        full:
            is_enabled: false            # default false
            host: http://site.com       # with scheme (http|https), default null, url validate
            status_code: 301            # default 302
            action: redirect            # redirect, no_redirect, redirect_without_path
        mobile:
            is_enabled: false            # default false
            host: http://m.site.com     # with scheme (http|https), default null, url validate
            status_code: 301            # default 302
            action: redirect            # redirect, no_redirect, redirect_without_path
        tablet:
            is_enabled: false            # default false
            host: http://t.site.com     # with scheme (http|https), default null, url validate
            status_code: 301            # default 302
            action: redirect            # redirect, no_redirect, redirect_without_path
        detect_tablet_as_mobile: true   # default false
    switch_device_view:
        save_referer_path: true        # default true
                                        # true  redirectUrl = http://site.com/current/path?currentQuery=string
                                        # false redirectUrl = http://site.com
    service:
        mobile_detector: mobile_detect.mobile_detector.default
    cookie_key: "device_view"                     # default
    cookie_expire_datetime_modifier: "+1 month"   # default
    switch_param: "device_view"                   # default
    #device_view_class: "SunCat\MobileDetectBundle\Helper\DeviceView"
    #request_response_listener_class: "SunCat\MobileDetectBundle\EventListener\RequestResponseListener"
    #twig_extension_class: "SunCat\MobileDetectBundle\Twig\Extension\MobileDetectExtension"
