<?php

namespace AppBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * AreaRepository
 *
 * This class was generated by the DQL ORM. Add your own custom
 * repository methods below.
 */
class AreaRepository extends EntityRepository
{
    public function getWrappedList($parent, $items)
    {
        return array(
            'name' => 'area',
            'parent' => $parent,
            'items' => $items,
            'columns' => 'two'
        );
    }
}
