<?php

namespace AppBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * BlackListRepository
 *
 * This class was generated by the DQL ORM. Add your own custom
 * repository methods below.
 */
class BlackListRepository extends EntityRepository
{
}
