AppBundle\Entity\User:
    properties:
        email:
            - Email:
                message: דוא"ל לא תקין
                checkMX: true
                groups: [sign_up_one, profile_one]

        password:
            - Length:
                min: 7
                minMessage: על הסיסמה להכיל בין 7 ל-15 תווים
                max: 15
                maxMessage: על הסיסמה להכיל בין 7 ל-15 תווים
                groups: [sign_up_one, change_password]

        purposes:
            - Count:
                min: 1
                minMessage: יש למלא את שדה "כאן למטרת"
                groups: [sign_up_two, profile_two]

        about:
            - Length:
                min: 10
                minMessage: שדה "על עצמי" חייב להכיל לפחות 10 תווים
                groups: [sign_up_three, profile_three]

        looking:
            - Length:
                min: 10
                minMessage: שדה "מה אני מחפש" חייב להכיל לפחות 10 תווים
                groups: [sign_up_three, profile_three]

        veggieReasons:
            - Count:
                min: 1
                minMessage: יש למלא את שדה "אני צמחוני/טבעוני"
                groups: [sign_up_three, profile_three]

        interests:
            - Count:
                min: 1
                minMessage: עליך לבחור לפחות תחום עניין אחד
                groups: [sign_up_three, profile_three]

    constraints:
        - Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity:
            fields: [username]
            message: שם משתמש כבר קיים במערכת
            groups: [sign_up_one, profile_one]

        - Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity:
            fields: [email]
            message: דוא"ל כבר קיים במערכת
            groups: [sign_up_one, profile_one]